name: spooky
description: Minimalist application to write stories, notes, diary!
publish_to: none
version: 1.4.1+118
environment:
  sdk: ">=2.17.0 <3.0.0"

# flutter pub upgrade --major-versions
# flutter pub outdated
dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^1.9.0
  animated_clipper: ^0.2.0+2
  animations: ^2.0.7
  awesome_notifications: ^0.7.5
  azlistview: ^2.0.0
  bubble_lens:
    git:
      url: https://github.com/juniorise/bubble_lens.git
      ref: master
  cached_network_image: ^3.2.1
  community_material_icon: ^5.9.55
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.4
  desktop_window: ^0.4.0
  dynamic_color: ^1.6.6
  easy_localization: ^3.0.2
  cloud_firestore: ^4.9.0
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  # firebase_remote_config: ^4.2.5
  firebase_storage: ^11.2.6
  flutter_cupertino_datetime_picker:
    git:
      url: https://github.com/juniorise/flutter_cupertino_datetime_picker.git
      ref: 3.0.2
  flutter_facebook_auth: ^6.0.1
  facebook_app_events:
    git:
      url: https://github.com/juniorise/flutter_facebook_app_events.git
      ref: kit-16-1-3
  flutter_markdown: ^0.6.17+1
  flutter_phoenix: ^1.1.1
  flutter_quill: ^7.4.2
  flutter_screen_lock: ^7.0.4
  flutter_secure_storage: ^8.0.0
  flutter_sticky_header: ^0.6.5
  flutter_weather_bg_null_safety:
    git:
      url: https://github.com/juniorise/flutter_weather_bg_null_safety.git
  fluttertoast: ^8.2.2
  fuzzy: ^0.4.0-nullsafety.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  googleapis: ^11.4.0
  http: ^1.1.0
  image_picker: ^1.0.2
  in_app_purchase: ^3.1.8
  json_annotation: ^4.8.1
  just_audio: ^0.9.34
  local_auth: ^2.1.6
  logger: ^2.0.1
  material_color_utilities: ^0.5.0
  miniplayer: ^1.0.1
  package_info_plus: ^4.2.0
  path: ^1.8.3
  path_provider: ^2.1.0
  provider: ^6.0.5
  quick_actions: ^1.0.5
  rect_getter: ^1.1.0
  responsive_builder: ^0.7.0
  restart_app: ^1.2.1
  shared_preferences: ^2.2.0
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  swipeable_page_route: ^0.4.0
  timezone: ^0.9.2
  tuple: ^2.0.2
  url_launcher: ^6.1.12
  wave: ^0.2.2
  encrypt: ^5.0.1
  html_character_entities: ^1.0.0+1
  simple_animations: ^5.0.2
  launch_review: ^3.0.1
  in_app_update: ^4.2.0
  flutter_custom_tabs: ^1.0.4
  flutter_cache_manager: ^3.3.1
  photo_view: ^0.14.0
  objectbox: ^2.2.1
  objectbox_flutter_libs: any
  flat_buffers: ^2.0.5
  device_info_plus: ^9.0.3
  app_settings: ^5.0.0
  flutter_signin_button: ^2.0.0
  visibility_detector: ^0.4.0+2
  flutter_countdown_timer: ^4.1.0
  day_night_time_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.0
  dismissible_page: ^1.0.1
  image_cropper: ^5.0.0
  new_version_plus: ^0.0.11
  string_similarity: ^2.0.0
  scroll_to_index: ^3.0.1
  confetti: ^0.7.0
  japx: ^2.1.0
  easy_localization_loader:
    git:
      url: https://github.com/aissat/easy_localization_loader.git
      ref: master
  string_validator: ^1.0.0
  popover: ^0.2.8+2
  navigation_history_observer: ^1.1.0
  tab_indicator_styler: ^2.0.0
  dio: ^5.4.0

  # unused:
  # objectbox_sync_flutter_libs: for ObjectBox Sync
  # injectable: ^1.5.3
  # open_file: ^3.2.1
  # scroll_to_index: ^3.0.1
  # stacked_services: ^0.8.25
  # visibility_detector: ^0.3.3
  # intl: ^0.17.0
  # flutter_keyboard_visibility: ^5.2.0
  # open_settings: ^2.0.2
  # googleapis_auth: ^1.3.1
  # simple_animations: ^4.0.2
  # expandable_text: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.4
  objectbox_generator: any

  # unused:
  # injectable_generator: ^1.5.3
  # change_app_package_name: ^1.1.0
  # flutter_native_splash: ^2.2.0+1
  # dependency_validator: ^3.2.0 # pub run dependency_validator

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/licenses/
    - translations/
    - assets/illustrations/
    - assets/emoji-64/
    - assets/sounds/sounds.json
    - assets/fonts/Quicksand/
