// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1irguW9pG5WbEz8rkCebNJTmTeYvHe1U',
    appId: '1:552632887204:web:b0ca0bb04bc6a383150331',
    messagingSenderId: '552632887204',
    projectId: 'my-notes-ssoad',
    authDomain: 'my-notes-ssoad.firebaseapp.com',
    storageBucket: 'my-notes-ssoad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvMCJq3G9HPr4mAI0MszdzT1cfnbaiHPM',
    appId: '1:552632887204:android:3f1b6168efc2f4cb150331',
    messagingSenderId: '552632887204',
    projectId: 'my-notes-ssoad',
    storageBucket: 'my-notes-ssoad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOR7hBhKhfH0hgsOTIehCbeJTaCEEUNTg',
    appId: '1:552632887204:ios:535e7085a0e095c8150331',
    messagingSenderId: '552632887204',
    projectId: 'my-notes-ssoad',
    storageBucket: 'my-notes-ssoad.appspot.com',
    androidClientId: '552632887204-64isfgvsgbk9k755tf9flch46f67qnvr.apps.googleusercontent.com',
    iosClientId: '552632887204-t1eg3bekgsa3pvns29mmd9lsim6joj8h.apps.googleusercontent.com',
    iosBundleId: 'com.juniorise.spooky.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOR7hBhKhfH0hgsOTIehCbeJTaCEEUNTg',
    appId: '1:552632887204:ios:46a7b6164957678b150331',
    messagingSenderId: '552632887204',
    projectId: 'my-notes-ssoad',
    storageBucket: 'my-notes-ssoad.appspot.com',
    androidClientId: '552632887204-64isfgvsgbk9k755tf9flch46f67qnvr.apps.googleusercontent.com',
    iosClientId: '552632887204-0fh2k0vi1niqbnl4a747p0q7eriubsin.apps.googleusercontent.com',
    iosBundleId: 'com.example.spooky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1irguW9pG5WbEz8rkCebNJTmTeYvHe1U',
    appId: '1:552632887204:web:39570d78918fa0aa150331',
    messagingSenderId: '552632887204',
    projectId: 'my-notes-ssoad',
    authDomain: 'my-notes-ssoad.firebaseapp.com',
    storageBucket: 'my-notes-ssoad.appspot.com',
  );
}
